@import "./color_schemes/dark";

title: How to Read Short Stories
description: A beginner's guide on how to read short stories as a writer
theme: just-the-docs

url: https://olivia530.github.io/short-stories

color_scheme: dark

nav_enabled: false
search_enabled: false

callouts:
  tip:
    title: Tip
    color: green
  question:
    title: Question
    color: purple
