title: How to Read Short Stories as a Writer
description: A beginner's guide on how to read short stories as a writer
theme: just-the-docs

url: https://olivia530.github.io/short-stories

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/olivia530/short-stories
